name: Deno
on: [push]

env:
  DENO_CACHE_DIR: /.deno_cache

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Set up Deno
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      # Cache dependencies
      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ${{ env.DENO_CACHE_DIR }}
          key: ${{ hashFiles('deno.lock') }}

      # Run checks
      - name: Check formatting
        run: deno fmt --check
      - name: Check linting
        run: deno lint
      - name: Run tests
        run: deno test --parallel
